# Generated by Django 5.2.6 on 2025-10-08 23:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_horariodisponible_serviciocorte_alter_cita_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('es_peluquero', models.BooleanField(default=False)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='HorarioDisponible',
        ),
        migrations.AlterModelOptions(
            name='cita',
            options={'ordering': ['-fecha', '-hora']},
        ),
        migrations.AlterModelOptions(
            name='serviciocorte',
            options={},
        ),
        migrations.AddField(
            model_name='cita',
            name='apellido_cliente',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cita',
            name='correo_cliente',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='cita',
            name='nombre_cliente',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cita',
            name='peluquero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_asignadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cita',
            name='telefono_cliente',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='cita',
            name='hora',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='cita',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citas', to=settings.AUTH_USER_MODEL),
        ),
    ]
