# Generated by Django 5.2.6 on 2025-10-12 16:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0003_perfilusuario_delete_horariodisponible_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cita',
            unique_together={('fecha', 'hora', 'peluquero')},
        ),
    ]
