# Generated by Django 5.2.6 on 2025-10-13 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0004_alter_cita_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='motivo_cancelacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='motivo_reagendamiento',
            field=models.TextField(blank=True, null=True),
        ),
    ]
